"""PDF report generation for monthly savings."""

from datetime import datetime
from io import BytesIO
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_monthly_pdf(user: dict, snapshot: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("Smart Energy AI — Monthly Savings Report", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"User: {user.get('full_name', 'N/A')}", styles["Normal"]))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    story.append(Spacer(1, 20))
    data = [
        ["Metric", "Value"],
        ["Monthly Usage (kWh)", str(snapshot.get("monthly_kwh", 0))],
        ["Estimated Bill (₹)", str(snapshot.get("estimated_bill", 0))],
        ["Carbon Footprint (kg)", str(snapshot.get("carbon_kg", 0))],
        ["Savings Potential (₹)", str(snapshot.get("savings_potential", 0))],
    ]
    table = Table(data, colWidths=[200, 200])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0ea5e9")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f9ff")]),
    ]))
    story.append(table)
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This report was generated by Smart Energy AI. Connect ESP32 + SCT-013 for live hardware data.",
        styles["Italic"],
    ))
    doc.build(story)
    return buffer.getvalue()
